---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magellanic.fullname" . }}-service
spec:
  ports:
    {{- range .Values.magellanic.services }}
    - port: {{ .servicePort }}
      name: {{ .name }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    app: {{ template "magellanic.name" . }}-core
  sessionAffinity: {{ .Values.magellanic.sessionAffinity }}
  type: {{ .Values.magellanic.type }}
