{{- if .Values.magellanicAdmin.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magellanic.fullname" . }}-admin-service
spec:
  ports:
    {{- range .Values.magellanic.services }}
    - port: {{ .servicePort }}
      name: {{ .name }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    app: {{ template "magellanic.name" . }}-admin-core
  sessionAffinity: {{ .Values.magellanic.sessionAffinity }}
  type: {{ .Values.magellanic.type }}
{{- end }}
