{{- if .Values.magellanic.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "magellanic.fullname" . }}-core-sa
  annotations:
      {{- range $key, $value := .Values.magellanic.serviceAccount.annotations }}
        {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}