version: '3.8'

x-common-variables: &common-variables
  PORT: 4000
  GRPC_SERVER_URL: magellanic-ledger:4000
  NODE_ENV: production
  FRONT_URL: http://127.0.0.1:3000
  MAGELLANIC_ADMIN_URL: http://127.0.0.1:3001
  MAGELLANIC_DOMAIN: localhost
  SQL_HOST: magellanic-metadata
  SQL_PORT: 5432
  SQL_USERNAME: magellanic
  SQL_PASSWORD: ChangeMe
  SQL_DBNAME: magellanic
  POSTGRES_USER: magellanic
  POSTGRES_PASSWORD: ChangeMe
  POSTGRES_DB: magellanic
  SQL_USE_SSL: 0
  GUACD_PORT: 4822
  GUACD_HOST: magellanic-remote
  AES_KEY: bad4d2ca79866e4b836da2c266bd3a8c3c700ddf8f51ea900ad62478f9c51b7b
  ACCESS_TOKEN_EXPIRES_IN: 3600
  REFRESH_TOKEN_EXPIRES_IN: 3600
  TOKENS_ROTATION_INTERVAL_MINUTES: 1
  REDIS_HOST: magellanic-queue
  REDIS_PORT: 6379
  MFA_RELYING_PARTY: Magellanic
  MAILER_AUTH: 0
  MAILER_HOST: smtp.magellanic.one
  MAILER_PORT: 25
  MAILER_USER: admin@mail.com
  MAILER_PASS: ChangeMe
  MAILER_FROM: ChangeMe <admin@mail.com>

services:
  magellanic-core-initdb:
    image: ${MAGELLANIC_IMAGE_REGISTRY}/magellanic-backend:af867e58
    container_name: magellanic-init
    restart: on-failure
    depends_on:
      - magellanic-metadata
      - queue
    entrypoint: /bin/sh
    command:
      - -c
      - yarn migrate:latest && yarn seed:run
    environment:
      <<: *common-variables
    networks:
      - magellanic

  magellanic-core:
    image: ${MAGELLANIC_IMAGE_REGISTRY}/magellanic-backend:af867e58
    container_name: magellanic-core
    restart: always
    depends_on:
      - magellanic-core-initdb
      - magellanic-metadata
      - magellanic-remote
      - queue
    ports:
      - 4000:4000
    environment:
      <<: *common-variables
    networks:
      - magellanic

  magellanic-ledger:
    image: ${MAGELLANIC_IMAGE_REGISTRY}/magellanic-ledger:d1ae455b
    container_name: magellanic-ledger
    restart: always
    depends_on:
      - magellanic-core-initdb
      - magellanic-remote
      - queue
    environment:
      <<: *common-variables
    networks:
      - magellanic

  admin:
    image: ${MAGELLANIC_IMAGE_REGISTRY}/magellanic-admin:74496987
    container_name: magellanic-admin
    restart: always
    environment:
      PORT: 3001
      API_URL: http://127.0.0.1:4000
      WS_URL: ws://127.0.0.1:4000
    depends_on:
      - magellanic-core
    ports:
      - 3001:3001
    networks:
      - magellanic

  frontend:
    image: ${MAGELLANIC_IMAGE_REGISTRY}/magellanic-frontend:a13a2b78
    container_name: magellanic-frontend
    restart: always
    environment:
      PORT: 3000
      API_URL: http://127.0.0.1:4000
      WS_URL: ws://127.0.0.1:4000
    depends_on:
      - magellanic-core
    ports:
      - 3000:3000
    networks:
      - magellanic

  magellanic-metadata:
    image: ${MAGELLANIC_IMAGE_REGISTRY}/magellanic-services:postgres-15.3
    container_name: magellanic-metadata
    restart: always
    environment:
      <<: *common-variables
    volumes:
      - metadata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "vault" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - magellanic

  magellanic-remote:
    container_name: magellanic-remote
    image: ${MAGELLANIC_IMAGE_REGISTRY}/magellanic-services:mgld-15.3
    restart: always
    ports:
      - 4822:4822
    volumes:
      - ./drive:/drive:rw
      - ./record:/record:rw
    networks:
      - magellanic

  queue:
    image: ${MAGELLANIC_IMAGE_REGISTRY}/magellanic-services:redis-7.0.12
    container_name: magellanic-queue
    restart: always
    volumes:
      - redis:/data
    networks:
      - magellanic

networks:
  magellanic:
    name: magellanic

volumes:
  graphdb:
  metadata:
  redis:
